version: '3'

services:
  php-app:
    image: ghcr.io/robertalex42/my-php-app:latest
    container_name: php-app
    restart: always

  caddy:
    image: caddy:latest
    container_name: caddy
    ports:
      - "80:80"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile

